### ISSUE TITLE
[Bug] - No such host is known.

### ISSUE THREAD

**Issue by ghost** [Rikux3/UsmToolkit#4]
I get this error everytime I try to install the dependencies, however, I figured out how to fix it. If you can, update the download URLs as they're down.

**Comment by ghost** [comment]
New URLs:
```json
{
    "Vgmstream" : "https://github.com/bnnm/vgmstream-builds/raw/master/bin/vgmstream-latest-test-u.zip",
    "FFmpeg" : "https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip"
}
```

**Comment by KojoBailey** [comment]
Even with the new URLs, the tool is unable to locate something... Here's my console output:

```
PS C:\Users\kojom\Downloads\publish> ./UsmToolkit.exe convert ./opening.usm
File: ./opening.usm
Demuxing...
adx audio detected, convert to wav...
FATAL ERROR: The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at UsmToolkit.Helpers.ExecuteProcess(String fileName, String arguments)
   at UsmToolkit.ConvertCommand.JoinOutputFile(CriUsmStream usmStream)
   at UsmToolkit.ConvertCommand.Process(String fileName)
   at UsmToolkit.ConvertCommand.OnExecute(CommandLineApplication app)
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.Invoke(MethodInfo method, Object instance, Object[] arguments)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](CommandLineContext context)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](IConsole console, String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute[TApp](String[] args)
   at UsmToolkit.Program.Main(String[] args)
```

It does successfully create the ADX and M2V however, so I'm not sure what file it's unable to locate.

I'm running all default configs except the download URLs in `deps.json`, which I used to install ffmpeg and vgmstream to the directory.

**Edit:** I found a modification of this tool, and it works fine: https://git.adawesome.tech/abheekd/usm-toolkit
